const vn = {
  error: "Lỗi",
  success: "Thành công",
  warning: "Cảnh báo",
  info: "Thông tin",
  notice: "Thông báo",
  selectValue: "Chọn giá trị",
  typeFilterValue: "Nhập giá trị lọc",
  valueNotInSelects: "Giá trị không có trong danh sách",
  cannotEmpty: "không được để trống",
  onlyDigit: "chỉ được bao gồm số",
  invalidPhoneNumber: "Số điện thoại phải là số từ 9 - 11 ký tự",
  invalidIdentityNumber: "Số CCCD phải là số có 9 hoặc 12 ký tự",
  invalidEmail: "Email sai định dạng",
  cannotBiggerToday: "không thể lớn hơn hôm nay",
  male: "Nam",
  female: "Nữ",
  other: "Khác",
  checkAgain: "Vui lòng kiểm tra lại",
  notInSelects: "không có trong danh sách",
  createMaterial: "Thêm mới nguyên vật liệu",
  updateMaterial: "Cập nhật nguyên vật liệu",
  duplicateMaterial: "Nhân bản nguyên vật liệu",
  createWarehouse: "Thêm mới kho ngầm định",
  updateWarehouse: "Cập nhật kho ngầm định",
  duplicateMaterial: "Nhân bản kho ngầm định",
  deletedMaterial: "Đã xoá nguyên vật liệu",
  delete: "Xoá",
  deleted: "Đã xoá",
  cannotDelete: "Không thể xoá",
  deleteConfirm: "Bạn có chắc chắn xoá",
  material: "nguyên vật liệu",
  titleMaterials: "Nguyên vật liệu",
  titleHome: "Tổng quan",
  accountingAmis: "AMIS Kế toán",
  materialList: "Danh sách nguyên vật liệu",
  materialListFileName: "Danh_sach_nguyen_vat_lieu",
  selectedMaterials: "nguyên vật liệu đã chọn",
  reloadedData: "Đã làm mới dữ liệu",
  reload: "Nạp",
  create: "Thêm",
  createNew: "Thêm mới",
  created: "Đã thêm",
  duplicate: "Nhân bản",
  duplicated: "Đã nhân bản",
  updated: "Đã cập nhật",
  invalidFormMessage: "Một số trường không hợp lệ. Vui lòng kiểm tra lại.",
  materialCode: "Mã nguyên vật liệu",
  identity: "Số CCCD",
  phone: "Điện thoại di động",
  userMsg500: "Có lỗi xảy ra. Vui lòng kiểm tra lại.",
  userMsg400: "Yêu cầu không hợp lệ. Vui lòng kiểm tra lại.",
  noContent: "Không có dữ liệu",
  save: "Cất",
  saveAdd: "Cất và thêm",
  saveChange: "Cất thay đổi",
  saveChangeConfirm:
    "Dữ liệu đã bị thay đổi so với lúc đầu.\nBạn có muốn cất không?",
  gotIt: "Đã hiểu",
  cancel: "Huỷ",
  no: "Không",
  questionNo: "không?",
  duplicatedMaterialCode: "Mã nguyên vật liệu bị trùng",
  mustLessThan: "phải nhỏ hơn",
  char: "ký tự",
  cannotConnectServer: "Kết nối Internet bị gián đoạn. Vui lòng kiểm tra lại.",
  futureFeature: "Chức năng sắp được hoàn thiện. Vui lòng thử lại sau.",
  connectTimeOut: "Quá thời gian kết nối. Vui lòng thử lại.",
  serverNoResponse: "Máy chủ không phản hồi. Vui lòng thử lại sau.",
  busySystem: "Hệ thống đang bận. Vui lòng thử lại sau.",
  contain: "Chứa",
  notContain: "Không chứa",
  equal: "Bằng",
  less: "Nhỏ hơn",
  more: "Lớn hơn",
  lessEqual: "Nhỏ hơn hoặc bằng",
  moreEqual: "Lớn hơn hoặc bằng",
  notEqual: "Không bằng",
  empty: "Rỗng",
  startWith: "Bắt đầu bằng",
  endWith: "Kết thúc bằng",
  before: "Trước",
  after: "Sau",
  day: "Ngày",
  monthEqual: "Có tháng bằng",
  yearEqual: "Có năm bằng",
  month: "Tháng",
  typeMonth: "Nhập tháng",
  year: "Năm",
  typeYear: "Nhập năm",
  filterValue: "Giá trị lọc",
  filter: "Lọc",
  sort: "Sắp xếp",
  invalid: "không hợp lệ",
  searchResult: "Kết quả tìm kiếm",
  required: "Bắt buộc",
  actionMany: "Thực hiện hàng loạt",
  fix: "Sửa",
  unselect: "Bỏ chọn",
  removeFilter: "Bỏ lọc",
  removeSearch: "Bỏ tìm kiếm",
  today: "Hôm nay",
  removeAllFilters: "Bỏ tất cả lọc",
  searchMaterial: "Tìm kiếm theo mã, tên, ghi chú",
  searchMaterialShort: "Tìm theo mã, tên, ghi chú",
  searchInList: "Tìm kiếm trong danh sách",
  exportToExcel: "Xuất file excel",
  export: "Xuất khẩu",
  reloadData: "Làm mới",
  invalidDateddMMyyyy: "phải có định dạng dd/MM/yyyy",
  invalidDateyyyyMMdd: "phải có định dạng yyyy/MM/dd",
  invalidDate: "không hợp lệ",
  total: "Tổng",
  selectedCount: "Đã chọn",
  percentage: "Tỉ lệ",
  selected: "đã chọn",
  unSelect: "Bỏ chọn",
  home: "Tổng quan",
  record: "Bản ghi",
  recordsPerPage: "Số bản ghi/trang",
  getNewCode: "Lấy mã mới",
  appName: "MISA CukCuk",
  feedback: "Phản hồi",
  page: "Trang",
  on: "trên",
  result: "kết quả",
  display: "Hiển thị",
  no: "Không",
  yes: "Có",
  apply: "Áp dụng",
  help: "Giúp",
  manageRestaurant: "CUKCUK - Quản lý nhà hàng",
  fillNameBeforeGetCode: "Vui lòng điền Tên trước khi lấy mã",
  words: "Các từ",
  wordsIn: "Các từ trong",
  startByAlphabet: "phải bắt đầu bằng chữ cái",
  errorNameCannotGetCode: "Tên bị lỗi không thể lấy mã mới",
  conversionUnit: "Đơn vị chuyển đổi",
  addRow: "Thêm dòng",
  deleteRow: "Xoá dòng",
  multiple: "nhân",
  divide: "chia",
  unfollow: "Ngừng theo dõi",
  used: "đã được sử dụng",
  cannotDuplicated: "không được trùng",
  cannotDuplicatedWith: "không được trùng với",
  duplicatedWith: "bị trùng với",
  and: "Và",
  or: "Hoặc",
  doubleClick: "Nháy đúp chuột",
  toResetPosition: "để trở về giữa màn hình",
  createUnit: "Thêm mới đơn vị tính",
  materialCode: "Mã nguyên vật liệu",
  materialName: "Tên nguyên vật liệu",
  minimumInventory: "SL tồn tối thiểu",
  minimumInventoryFullTitle: "Số lượng tồn tối thiểu",
  unit: "Đơn vị tính",
  warehouse: "Kho ngầm định",
  note: "Ghi chú",
  isUnfollow: "Ngừng theo dõi",
  name: "Tên",
  unitName: "Tên đơn vị",
  code: "Mã",
  expiryTime: "Hạn sử dụng",
  timeUnit: "Đơn vị thời gian",
  operator: "Phép tính",
  description: "Mô tả",
  rowIndex: "STT",
  rowIndexFullTitle: "Số thứ tự",
  conversionRate: "Tỉ lệ chuyển đổi",
  warehouseCode: "Mã kho",
  warehouseName: "Tên kho",
  address: "Địa chỉ",
  typeNumber: "Nhập số",
};

const resources = {
  vn: vn,
};
export default resources;
